### ISSUE TITLE
Update GHA R CMD check workflow

### ISSUE THREAD

**Issue by maelle** [ropensci/qualR#2]
By running `use_github_action_check_standard()` and overwriting the current workflow file. :smile_cat: (I see the current workflow still uses v1 of things)

**Comment by maelle** [comment]
Why are there two R CMD check workflows by the way?

**Comment by quishqa** [comment]
Thanks! It worked. All tests passed and the double R CMD check was deleted.

**Comment by maelle** [comment]
:rocket: :tada:
